module.exports = {
	SOURCE_TYPE_BUY_IN : 'BuyIn'
	,SOURCE_TYPE_WIN : 'Win'
	,SOURCE_TYPE_PROMO : 'Promo'
	,SOURCE_TYPE_CANCEL_REG : 'Cancel'
	,SOURCE_TYPE_CASHOUT : 'Cashout'
	,SOURCE_TYPE_DEPOSIT : 'Deposit'
	,SOURCE_TYPE_ACCELERATOR_BUY: 'BuyAccelerator'
	,SOURCE_TYPE_GRANT: 'Grant'
	,SOURCE_TYPE_SET: 'Set'

	,INVITER_HUMAN:0
	,INVITER_GROUP:1 // groups in VK (maybe need another for FB groups)
	,INVITER_SITE:2 // partner sites
	,INVITER_VIDEO:3 // youtube

	,PAYMENT_TOURNAMENT:0
	,PAYMENT_ACCELERATOR:1
	,PAYMENT_FULLFILL:2

	,MESSAGE_READ:1

	,NOTIFICATION_GIVE_ACCELERATOR:1 // give to user an accelerator
	,NOTIFICATION_GIVE_MONEY:2 // give user money
	,NOTIFICATION_ACCEPT_MONEY:3 // give money to a user if he clicks on button
	
	,NOTIFICATION_MARATHON_PRIZE:4 // give user money
	,NOTIFICATION_FORCE_PLAYING:5 // force playing
	,NOTIFICATION_CUSTOM:6 // custom message. needs fields
	,NOTIFICATION_UPDATE:7 // update page
	,NOTIFICATION_FIRST_MESSAGE:8
	,NOTIFICATION_MARATHON_CURRENT:9
	,NOTIFICATION_AUTOREG:10
	,NOTIFICATION_JOIN_VK:11

	,NOTIFICATION_WIN_MONEY:12
	,NOTIFICATION_LOSE_TOURNAMENT:13
	,NOTIFICATION_ADVICE:14

	,USER_STATUS_NEWBIE: 1

	// ,MESSAGE_TYPE_
}