module.exports = {
	SOURCE_TYPE_BUY_IN : 'BuyIn'
	,SOURCE_TYPE_WIN : 'Win'
	,SOURCE_TYPE_PROMO : 'Promo'
	,SOURCE_TYPE_CANCEL_REG : 'Cancel'
	,SOURCE_TYPE_CASHOUT : 'Cashout'
	,SOURCE_TYPE_DEPOSIT : 'Deposit'
	,SOURCE_TYPE_ACCELERATOR_BUY: 'BuyAccelerator'
	,SOURCE_TYPE_GRANT: 'Grant'
}