mkdir -p /tournaments
mkdir -p /tournaments/app
mkdir -p /tournaments/backups
	mkdir -p /tournaments/backups/regular
	mkdir -p /tournaments/backups/onDemand
mkdir -p /tournaments/configs
	mkdir -p /tournaments/configs/app
	mkdir -p /tournaments/configs/games
	mkdir -p /tournaments/configs/nginx
