echo "START SH SCRIPT WORKS!!"
gnome-terminal -x sh -c 'node /home/gaginho/project/NODE/DBServer.js; exec bash'
echo 'SCRIPT DBServer.js WORKS!!'
gnome-terminal -x sh -c 'node /home/gaginho/project/NODE/FrontendServer.js; exec bash'
echo 'SCRIPT FrontendServer.js WORKS!!'
gnome-terminal -x sh -c 'node /home/gaginho/project/NODE/BalanceServer.js; exec bash'
echo 'SCRIPT BalanceServer.js WORKS!!'
gnome-terminal -x sh -c 'node /home/gaginho/project/NODE/TournamentServer.js; exec bash'
echo 'SCRIPT TournamentServer.js WORKS!!'
gnome-terminal -x sh -c 'node /home/gaginho/project/NODE/GameFrontendServer.js; exec bash'
echo 'SCRIPT GameFrontendServer.js WORKS!!'
gnome-terminal -x sh -c 'node /home/gaginho/project/NODE/PingPongServer.js; exec bash'
echo 'SCRIPT PingPongServer.js WORKS!!'
gnome-terminal -x sh -c 'node /home/gaginho/project/NODE/TournamentManager.js; exec bash'
echo 'SCRIPT TournamentManager.js WORKS!!'
gnome-terminal -x sh -c 'node /home/gaginho/project/NODE/initializer.js; exec bash'
echo 'SCRIPT initializer.js WORKS!!'
