const constants = {
  NOTIFICATION_GIVE_ACCELERATOR: 1,
  NOTIFICATION_GIVE_MONEY: 2,
  NOTIFICATION_ACCEPT_MONEY: 3, // give money to a user if he clicks on button

  NOTIFICATION_MARATHON_PRIZE: 4,
  NOTIFICATION_FORCE_PLAYING: 5,
  NOTIFICATION_CUSTOM: 6,
  NOTIFICATION_UPDATE: 7,

  NOTIFICATION_FIRST_MESSAGE: 8,
  NOTIFICATION_MARATHON_CURRENT: 9,

  NOTIFICATION_AUTOREG: 10,
  NOTIFICATION_JOIN_VK: 11,

  NOTIFICATION_WIN_MONEY: 12,
  NOTIFICATION_LOSE_TOURNAMENT: 13,

  NOTIFICATION_ADVICE: 14,
  NOTIFICATION_CARD_GIVEN: 15,
  NOTIFICATION_GIVE_PACK: 16,

  RARITY_RARE: 0,
  RARITY_LOW: 1,
  RARITY_MID: 2,
  RARITY_HIGH: 3,

  CARD_COLOUR_RED: 1,
  CARD_COLOUR_BLUE: 2,
  CARD_COLOUR_GREEN: 3,
  CARD_COLOUR_GRAY: 4,

  PAYMENT_TOURNAMENT: 0,
  PAYMENT_ACCELERATOR: 1,
  PAYMENT_FULLFILL: 2,
  PAYMENT_PACK: 3,

  ACTION_INITIALIZE: 'ACTION_INITIALIZE',
  ACTION_REGISTER_IN_TOURNAMENT: 'ACTION_REGISTER_IN_TOURNAMENT',
  ACTION_UNREGISTER_FROM_TOURNAMENT: 'ACTION_UNREGISTER_FROM_TOURNAMENT',
  ACTION_TEST: 'ACTION_TEST',
};

module.exports = constants;
